# fly.toml app configuration file generated for chatter-box on 2025-07-27T14:46:37-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatter-box'
primary_region = 'atl'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'

# Redis service configuration
[[services]]
  protocol = 'tcp'
  internal_port = 6379
  processes = ['redis']

  [[services.ports]]
    port = 6379
    handlers = ['pg_tls']
    force_https = false

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[processes]
  app = 'bin/rails server'
  redis = 'redis-server --appendonly yes'
